output_path = "sample/index-seeds-centrality"
host_centrality_store_path = "sample/centrality-on"
limit_warc_files = 1
batch_size = 512
autocommit_after_num_inserts = 5000
[warc_source]
type = "Local"
folder = "sample"
names = ["seeds.warc.gz"]
