//! Supplies immutable build metadata to the API without runtime environment or Git access.
//! The rendered document is retained in the binary and distributed as a build artefact.

#![deny(missing_docs)]

/// Licence of this service's source offer; upstream notices remain unchanged.
pub(crate) const LICENCE: &str = "AGPL-3.0-only";
/// Public repository for corresponding source discovery.
pub(crate) const REPOSITORY: &str = env!("CARGO_PKG_REPOSITORY");
/// Literal source offer generated by the same build as the metadata.
#[used]
pub(crate) static RENDERED_OFFER: &str = include_str!(concat!(env!("OUT_DIR"), "/SOURCE_OFFER.md"));

/// Build identity shared by the JSON endpoint and header.
pub(crate) struct Metadata {
    /// Full lowercase SHA-1, or unknown.
    pub(crate) revision: &'static str,
    /// Git, environment or unknown selection, represented in lowercase.
    pub(crate) revision_source: &'static str,
    /// Pinned tree URL for a known revision, otherwise the repository root.
    pub(crate) source_url: String,
}

/// Constructs metadata from compile-time values, never request-time environment.
pub(crate) fn embedded() -> Metadata {
    metadata(
        env!("AVA_SEARCH_REVISION"),
        env!("AVA_SEARCH_REVISION_SOURCE"),
    )
}

/// Constructs the URL for a build-validated identity, including an honest unknown case.
pub(crate) fn metadata(revision: &'static str, revision_source: &'static str) -> Metadata {
    Metadata {
        revision,
        revision_source,
        source_url: if revision == "unknown" {
            REPOSITORY.to_owned()
        } else {
            format!("{REPOSITORY}/tree/{revision}")
        },
    }
}
